language: swift
osx_image: xcode9.1
xcode_sdk: iphonesimulator11.1
before_install: rvm use $RVM_RUBY_VERSION
install: bundle install --without=documentation --path ../travis_bundle_dir
branches:
only:
- master
script:
- bundle exec fastlane test
after_success:
- bash <(curl -s https://codecov.io/bash) -t a31923ac-c821-47bb-8f97-1314528403c8 -J 'FizzBuzz'