fastlane_version "2.62.1"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "FizzBuzz",code_coverage: true)
    slather(
      output_directory: "coverage",
      scheme: "FizzBuzz",
      proj: "FizzBuzz.xcodeproj",
      workspace: "FizzBuzz.xcworkspace",
      cobertura_xml: true,
      travis_pro: true,
      verbose: true,
      ignore: ["**/UIViewController+Testeable.swift"])
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end